#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

RESULTS_FILE="wizard-results-issue-7.local.md"
FRIEND_STEPS_FILE="friend-steps-issue-7.local.md"

# record "line" appends a fact to the results file the next agent session
# reads to close ticket #7.
record() { printf -- '- %s\n' "$1" >> "$RESULTS_FILE"; }

printf '# Wizard results — ticket #7 (deploy target & access)\n\nRun: %s\n\n' "$(date '+%Y-%m-%d %H:%M')" > "$RESULTS_FILE"

# Settled in conversation (2026-09-03) — recorded up front, not re-asked:
record "Jacob's friend owns the entire v1 hosting chain: the 'jay-z-projects' Vercel scope, the Cloudflare account for amovieclub.com, the domain, AND the Foifoif GitHub account that owns the repos. Jacob has no admin anywhere; login sharing is ruled out."
record "Decision: the repo moves from the personal Foifoif account into a free GitHub org with Jacob and the friend both owners. A personal repo can't grant collaborators admin, which blocks the Vercel import today and Actions secrets + branch protection tomorrow; the org fixes all three and the cutover bus-factor."
record "Decision: v2 deploys under Jacob's own free Vercel account; preview URL is the platform *.vercel.app domain. The friend's remaining involvement is a short DNS checklist at cutover."

banner "Repo → GitHub org, then connect Vercel (ticket #7)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the free GitHub organization"
say "The org becomes the repo's home; you and your friend both own it."
open_url "https://github.com/organizations/plan"
step "Pick the Free plan."
step "Choose an org name (this becomes the repo URL prefix)."
step "'This organization belongs to' → your personal account."
ask GH_ORG "Org name, exactly as created:"
write_env GH_ORG "$GH_ORG"
record "GitHub org created: '$GH_ORG' (free plan), created by JacobFierro."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Invite your friend as co-owner"
open_url "https://github.com/orgs/$GH_ORG/people"
step "Invite the 'Foifoif' account. Role: Owner — co-ownership is the point;"
step "it also gives him the permission the repo transfer needs."
cat > "$FRIEND_STEPS_FILE" <<FRIEND
Steps for the Foifoif account owner (~2 minutes, no data is lost —
issues, labels and everything else move with the repo, and the old
URL redirects forever):

1. Accept the invitation to the '$GH_ORG' organization
   (email, or the banner at https://github.com/$GH_ORG).
2. Open https://github.com/Foifoif/movie_club_v2/settings
3. Scroll to the bottom ("Danger Zone") → "Transfer ownership"
   → "Transfer".
4. Under "New owner", pick: $GH_ORG
5. Type the repository name to confirm, and transfer.

That's it — nothing else changes for you. movie-club (v1) stays
exactly where it is.
FRIEND
say ""
say "Send him the message saved in $FRIEND_STEPS_FILE:"
say ""
sed 's/^/  │ /' "$FRIEND_STEPS_FILE"
pause "Invitation sent and message passed on? Press Enter."
record "Friend invited to '$GH_ORG' as Owner; transfer instructions handed off in $FRIEND_STEPS_FILE."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Wait for the repo transfer"
say "Checking whether $GH_ORG/movie_club_v2 exists yet…"
if gh api "repos/$GH_ORG/movie_club_v2" --jq .full_name >/dev/null 2>&1; then
  say "It's there — the transfer is complete."
  record "Repo transferred: now $GH_ORG/movie_club_v2."
else
  warn "Not transferred yet — that's expected if your friend hasn't done"
  warn "his part. Stop here and re-run this wizard once he has; your"
  warn "earlier answers re-fill with Enter."
  record "PENDING: transfer of movie_club_v2 into '$GH_ORG' not complete as of $(date '+%Y-%m-%d %H:%M'). Re-run scripts/confirm-deploy-target.sh after the friend transfers."
  finish
  exit 0
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Point this clone at the repo's new home"
say "Old Foifoif URLs redirect, but let's not rely on that locally."
git remote set-url origin "https://github.com/$GH_ORG/movie_club_v2.git"
say "origin → https://github.com/$GH_ORG/movie_club_v2.git"
record "Local git remote updated to $GH_ORG/movie_club_v2; other clones keep working via GitHub's redirect."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Import the repo into YOUR Vercel account"
say "Create a free Vercel account with 'Continue with GitHub' if needed."
open_url "https://vercel.com/new"
step "In the Git-namespace dropdown (top-left of the repo list), choose"
step "'Add GitHub Account' → select the '$GH_ORG' org → install the Vercel"
step "app with access to movie_club_v2."
step "Import movie_club_v2. Framework preset: Vite. Defaults → Deploy."
note "The repo has no app yet, so the first build may fail or deploy an"
note "empty page — fine; this proves the pipeline, not the app."
if confirm "Did the import complete without any payment/upgrade prompt?"; then
  record "Free tier confirmed: importing the project triggered no upgrade prompt."
else
  record "ATTENTION: Vercel showed a payment/upgrade prompt during import — free tier NOT confirmed."
fi
ask V2_VERCEL_SCOPE "Your Vercel account/scope name (as shown top-left):"
ask V2_VERCEL_PROJECT "The Vercel project name (e.g. movie-club-v2):"
write_env V2_VERCEL_SCOPE "$V2_VERCEL_SCOPE"
write_env V2_VERCEL_PROJECT "$V2_VERCEL_PROJECT"
record "v2 is connected: Vercel project '$V2_VERCEL_PROJECT' under Jacob's scope '$V2_VERCEL_SCOPE', importing $GH_ORG/movie_club_v2."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Record the *.vercel.app URL"
open_url "https://vercel.com/$V2_VERCEL_SCOPE/$V2_VERCEL_PROJECT/settings/domains"
step "Copy the <project>.vercel.app domain (not the per-deploy hash URL)."
ask V2_URL "Paste the full URL (https://....vercel.app):"
record "v2 preview URL: $V2_URL."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Where build-time env vars live"
say "Contributors' build-time config is injected by Vercel from Project →"
say "Settings → Environment Variables. Vite only exposes VITE_-prefixed vars."
open_url "https://vercel.com/$V2_VERCEL_SCOPE/$V2_VERCEL_PROJECT/settings/environment-variables"
step "Just confirm the page loads — nothing to set yet; the app doesn't exist."
pause "Seen it? Press Enter."
record "Build-time env vars live in Vercel: $V2_VERCEL_SCOPE/$V2_VERCEL_PROJECT → Settings → Environment Variables (VITE_ prefix required for client exposure). Only Jacob can edit them."

record "Wizard completed $(date '+%Y-%m-%d %H:%M')."
say "Results captured in $RESULTS_FILE (gitignored)."
say "Tell the wayfinder session it's done (or start a new one) to close #7."

finish
