#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ticket #6: create and expose the `v2` Postgres schema in the SHARED
# production Supabase project (the one serving amovieclub.com / v1).
# Everything here is additive to that project — the one forbidden command is
# `supabase db reset --linked`, which would destroy v1.

TOTAL_STAGES=11

# All outputs (.env.local, backups/, the results file) are repo-root-relative,
# wherever the script is launched from. The first real run was started from
# scripts/ and scattered its artifacts there.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

ENV_FILE=".env.local"

PROJECT_REF="schtizxdezxteulbvynp"
SUPA_URL="https://${PROJECT_REF}.supabase.co"
PUB_KEY="sb_publishable_BLeS65tH-8Fxd4nbAX8acA_TAIMtcNn"  # public by design
RESULTS_FILE="wizard-results-issue-6.local.md"

# record "line" appends a fact to the results file the next agent session
# reads to close ticket #6.
record() { printf -- '- %s\n' "$1" >> "$RESULTS_FILE"; }

# probe_movies BODY_FILE [extra curl args…] — GET v1's movies endpoint with the
# public key, body to BODY_FILE, HTTP code to stdout. The shared probe behind
# every isolation/regression check below.
probe_movies() {
  local body="$1"; shift
  curl -s -o "$body" -w '%{http_code}' \
    "$SUPA_URL/rest/v1/movies?select=*&limit=1" \
    -H "apikey: $PUB_KEY" "$@"
}

# Every table v1 actually queries (grepped from ../movie-club/js .from() calls).
# None of these may ever appear in v2's generated types.
V1_TABLES='bracket|bracket_history|members|monthly_events|movies|poll_options|poll_votes|polls|ratings|rsvps|settings|watchlist'

printf '# Wizard results — ticket #6 (v2 schema)\n\nRun: %s\n\n' "$(date '+%Y-%m-%d %H:%M')" > "$RESULTS_FILE"

banner "v2 schema: create + expose (ticket #6)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase CLI login"
say "Everything runs through the Supabase CLI via npx — no install, no Docker."
if npx supabase projects list >/dev/null 2>&1; then
  say "Already logged in — nothing to do."
else
  step "A browser will open; approve the CLI login."
  npx supabase login
fi
record "CLI login: ok"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Back up the public schema (v1's data)"
warn "v1 is LIVE on this project and the free tier keeps no backups."
say "Before touching anything we dump the whole public schema to backups/."
if ! command -v pg_dump >/dev/null 2>&1 && [[ ! -x /opt/homebrew/opt/libpq/bin/pg_dump ]]; then
  say "pg_dump is not installed. It comes with Homebrew's libpq (no server, no Docker)."
  if confirm "Run 'brew install libpq' now?"; then
    brew install libpq
  else
    warn "Cannot back up without pg_dump — stopping here rather than proceeding unbacked."
    exit 1
  fi
fi
PGDUMP="$(command -v pg_dump || echo /opt/homebrew/opt/libpq/bin/pg_dump)"
PGRESTORE="$(command -v pg_restore || echo /opt/homebrew/opt/libpq/bin/pg_restore)"
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/database"
step "Click 'Connect' (top of dashboard) if the URI isn't on this page."
step "Copy the SESSION POOLER connection string (port 5432, IPv4-friendly —"
step "the 'direct' one is IPv6-only on the free tier and may not work here)."
step "Replace [YOUR-PASSWORD] with the database password. If you don't have it,"
step "there's a 'Reset database password' button on the Database settings page."
ask_secret DB_URI "Paste the full postgresql:// URI (with password):"
mkdir -p backups
STAMP=$(date +%Y%m%d-%H%M%S)
BACKUP="backups/public-$STAMP.dump"
BACKUP_SQL="backups/public-$STAMP.sql"
say "Dumping schema 'public' (structure + data, pg_restore-able custom format)…"
"$PGDUMP" "$DB_URI" --schema=public --no-owner -Fc -f "$BACKUP"
say "Verifying it restores: decoding the whole archive back to plain SQL."
note "(A live restore rehearsal needs a second database, which this project"
note "doesn't have — a full pg_restore decode is the strongest check available.)"
DATA_SECTIONS=$("$PGRESTORE" --list "$BACKUP" | grep -c 'TABLE DATA' || true)
"$PGRESTORE" -f "$BACKUP_SQL" "$BACKUP"
TABLES=$(grep -cE '^CREATE TABLE' "$BACKUP_SQL" || true)
SIZE=$(du -h "$BACKUP" | cut -f1)
say "Wrote $BACKUP ($SIZE) — $TABLES tables, $DATA_SECTIONS data sections."
grep -E '^CREATE TABLE' "$BACKUP_SQL" | sed 's/^/    /'
say "Those should be all of v1's tables (movies, ratings, polls, …)."
if [[ "$TABLES" -eq 0 || "$DATA_SECTIONS" -eq 0 ]]; then
  warn "Empty or structure-only dump — do not proceed."
  exit 1
fi
if ! confirm "Does the table list look complete?"; then
  warn "Stopping — do not proceed on a bad backup."
  exit 1
fi
note "backups/ is gitignored; a production dump must never reach the public repo."
record "Backup: $BACKUP ($SIZE, $TABLES tables, $DATA_SECTIONS TABLE DATA sections; archive decoded end-to-end by pg_restore — live restore rehearsal impossible without a second database)"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Link this repo to the shared project"
say "Links the CLI to $PROJECT_REF so 'db push' knows its target."
step "It may prompt for the same database password you used above."
npx supabase link --project-ref "$PROJECT_REF"
record "Linked to project ref: $PROJECT_REF"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Push the v2 schema migration"
say "One tracked migration: CREATE SCHEMA v2 + the PostgREST grants."
say "Dry run first — read the plan:"
npx supabase db push --dry-run
warn "This applies to the LIVE project. It is additive (a new empty schema);"
warn "it does not touch the public schema. Never run 'supabase db reset' here."
if confirm "Apply the migration for real?"; then
  npx supabase db push
else
  warn "Stopping at your request — nothing was applied."
  exit 1
fi
record "Migration 20260902210137_create_v2_schema.sql pushed (CREATE SCHEMA v2 + grants)"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Expose the v2 schema to the API"
say "PostgREST only serves schemas listed in Exposed Schemas — a dashboard-only setting."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/api"
step "Find 'Exposed schemas' under Data API settings."
step "Add 'v2' to the list — LEAVE 'public' in place, v1 depends on it."
step "Save."
pause "Done?"
record "v2 added to Exposed schemas (public left in place)"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify schema isolation, both directions"
say "1/3 — a v2-profile client must reach the schema but NOT see v1's tables:"
V2_CODE=$(probe_movies /tmp/v2-probe.json -H "Accept-Profile: v2")
if [[ "$V2_CODE" == "200" ]]; then
  warn "FAIL: 'movies' is reachable through the v2 profile (HTTP 200). Isolation is broken — investigate before continuing."
  V2_VERDICT="FAIL — HTTP 200, v1 table visible through v2 profile"
elif grep -q 'PGRST106' /tmp/v2-probe.json; then
  warn "FAIL: the v2 schema is NOT in Exposed Schemas (PGRST106) — go back one stage and redo it."
  V2_VERDICT="FAIL — PGRST106, v2 not actually exposed"
elif grep -qE 'PGRST205|42P01' /tmp/v2-probe.json; then
  # PostgREST answers PGRST205 ("table not in schema cache") for a missing
  # table in an exposed schema — confirmed on the real run; 42P01 kept for
  # older PostgREST versions that pass the Postgres error through.
  say "  ✓ v2 profile is served (schema reachable) and cannot see public.movies"
  V2_VERDICT="PASS — schema reachable, v1 tables invisible (PGRST205/42P01)"
else
  warn "Unexpected response (HTTP $V2_CODE): $(cat /tmp/v2-probe.json)"
  V2_VERDICT="UNCLEAR — HTTP $V2_CODE, see wizard output"
fi
say "2/3 — the default profile must still serve v1:"
V1_MOVIES=$(probe_movies /dev/null)
if [[ "$V1_MOVIES" == "200" ]]; then
  say "  ✓ public.movies still served on the default profile (HTTP 200)"
else
  warn "FAIL: v1's movies endpoint returned HTTP $V1_MOVIES — v1 may be broken, investigate NOW."
fi
say "3/3 — generated types for --schema v2 must contain none of v1's 12 tables:"
npx supabase gen types typescript --linked --schema v2 > /tmp/v2-database.types.ts
if grep -qwE "($V1_TABLES)" /tmp/v2-database.types.ts; then
  warn "FAIL: v1 tables leaked into the v2 types — the whole point of the schema. Investigate:"
  grep -woE "($V1_TABLES)" /tmp/v2-database.types.ts | sort -u | sed 's/^/    /'
  TYPES_VERDICT="FAIL — v1 table names present"
else
  say "  ✓ gen types --schema v2 emits only v2 (currently empty) — no v1 leakage"
  TYPES_VERDICT="PASS — none of v1's 12 table names present"
fi
record "Isolation: v2 profile $V2_VERDICT · default profile→movies HTTP $V1_MOVIES (expect 200) · gen types --schema v2: $TYPES_VERDICT"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Google OAuth provider"
say "Google sign-in needs an OAuth client from Google Cloud, pasted into Supabase."
say "Docs, if anything below has moved: supabase.com/docs/guides/auth/social-login/auth-google"
open_url "https://console.cloud.google.com/apis/credentials"
step "Pick (or create) a project for the movie club."
step "Configure the OAuth consent screen if prompted (External, app name, your email)."
step "Create Credentials → OAuth client ID → type 'Web application'."
step "Authorized redirect URI — exactly: ${SUPA_URL}/auth/v1/callback"
step "Copy the Client ID and Client secret it shows you."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/providers"
step "Open the Google provider, toggle it ON, paste Client ID + secret, save."
pause "Done?"
record "Google OAuth provider: enabled"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Magic link on, self-signup OFF"
say "The club is invite-only: members are created by the admin, never by signup (#2)."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/providers"
step "Open the Email provider: ensure it's enabled; passwords may stay off — magic link is the email path."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/auth"
step "Find 'Allow new users to sign up' and turn it OFF."
step "Save. This is the enable_signup=false decision from issue #2 — it makes the"
step "OAuth gate hold: unknown Google accounts get rejected instead of registered."
pause "Done?"
record "Email magic link: enabled; 'Allow new users to sign up': OFF (enable_signup=false)"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Confirm v1 is undisturbed"
say "Auth changes apply project-wide, so prove the live site still works anonymously."
V1_CHECK=$(probe_movies /dev/null)
if [[ "$V1_CHECK" == "200" ]]; then
  say "  ✓ anonymous read on public.movies still works (HTTP 200)"
else
  warn "FAIL: HTTP $V1_CHECK — v1's anonymous access may be broken. Fix before leaving this stage."
fi
open_url "https://amovieclub.com"
step "Load the site, click into a movie or two, confirm it behaves normally."
if ! confirm "Does the live site still work?"; then
  warn "Do not walk away — revisit the auth settings until v1 works again."
  exit 1
fi
record "v1 regression check: REST HTTP $V1_CHECK; live site confirmed working by hand"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Settle a fact: Auth Hooks on the free tier?"
say "Issue #2 found the docs and pricing page contradict each other on this."
say "Nothing depends on it — we just want the true answer recorded."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/hooks"
step "Can you actually add a hook here, or is it gated behind a paid-plan banner?"
ask AUTH_HOOKS_ANSWER "What do you see? (e.g. 'available' / 'Pro-only banner'):"
record "Auth Hooks on free tier: $AUTH_HOOKS_ANSWER"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Record the working values"
say "The URL and publishable key are public by design and already sit in"
say ".env.example — verify them against the dashboard, then keep a local copy."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/api-keys"
step "Confirm the publishable key shown there matches: $PUB_KEY"
if ! confirm "Does it match?"; then
  ask PUB_KEY "Paste the correct publishable key:"
  warn "Also fix .env.example before merging the PR."
fi
write_env VITE_SUPABASE_URL "$SUPA_URL"
write_env VITE_SUPABASE_PUBLISHABLE_KEY "$PUB_KEY"
say "The sb_secret_ key and your personal access token must live OUTSIDE this"
say "repo (password manager; GitHub secrets when CI needs them)."
ask SECRETS_HOME "Where are the secret key + PAT stored? (e.g. '1Password'):"
record "Project ref: $PROJECT_REF · URL: $SUPA_URL · publishable key: $PUB_KEY (in .env.example)"
record "sb_secret_ key + PAT stored in: $SECRETS_HOME (never in the repo)"

record ""
record "Wizard completed $(date '+%Y-%m-%d %H:%M'). Next: run /wayfinder 1 — the session reads this file, posts the resolution on issue #6 and closes it."
finish
say "Results captured in $RESULTS_FILE (gitignored)."
say "Next: re-run /wayfinder 1 so the agent records the resolution and closes #6."
